### ISSUE TITLE
crash with commit 0c47f001

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#138]
Here is a sequence that seems to cause the crash.

Open multiple tabs
Shell/Execute Command -> xterm
close the tab in which the shell command was executed

```
#0  0x00002b7ed6658bd3 in QObject::~QObject() () at /lib64/libQt5Core.so.5
#1  0x00000000004efc53 in DocumentWidget::<lambda()>::operator()(void) const (this=0xafd87a0, __in_chrg=<optimized out>) at /tmp/nedit-ng/src/DocumentWidget.cpp:62
#2  0x00000000004efc53 in DocumentWidget::<lambda()>::operator()(void) const (this=<optimized out>, __ptr=0xafd87a0) at /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:76
#3  0x00000000004efc53 in DocumentWidget::<lambda()>::operator()(void) const (__p=0xafd87a0, this=<optimized out>) at /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:347
#4  0x00000000004efc53 in DocumentWidget::<lambda()>::operator()(void) const (this=<optimized out>) at /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:283
#5  0x00000000004efc53 in DocumentWidget::<lambda()>::operator()(void) const (__closure=__closure@entry=0x7ffe1d97f370) at /tmp/nedit-ng/src/DocumentWidget.cpp:4617
#6  0x00000000004f700d in DocumentWidget::processFinished(int, QProcess::ExitStatus) (this=0xaacc480, exitCode=9, exitStatus=<optimized out>)
    at /tmp/nedit-ng/GSL/include/gsl/gsl_util:74
#7  0x00002b7ed6651273 in QMetaObject::activate(QObject*, int, int, void**) () at /lib64/libQt5Core.so.5
#8  0x00002b7ed65b987f in QProcess::finished(int, QProcess::ExitStatus) () at /lib64/libQt5Core.so.5
#9  0x00002b7ed65c0633 in QProcessPrivate::_q_processDied() () at /lib64/libQt5Core.so.5
#10 0x00002b7ed65c5057 in QProcessPrivate::waitForFinished(int) () at /lib64/libQt5Core.so.5
#11 0x00002b7ed65ba302 in QProcess::waitForFinished(int) () at /lib64/libQt5Core.so.5
#12 0x00002b7ed65ba99a in QProcess::~QProcess() () at /lib64/libQt5Core.so.5
#13 0x00002b7ed65baa39 in QProcess::~QProcess() () at /lib64/libQt5Core.so.5
#14 0x00002b7ed6651d45 in QObjectPrivate::deleteChildren() () at /lib64/libQt5Core.so.5
#15 0x00002b7ed5a49472 in QWidget::~QWidget() () at /lib64/libQt5Widgets.so.5
#16 0x00000000004f0bc9 in DocumentWidget::~DocumentWidget() (this=0xaacc480, __in_chrg=<optimized out>) at /tmp/nedit-ng/src/DocumentWidget.cpp:615
#17 0x00000000004f0bf9 in DocumentWidget::~DocumentWidget() (this=0xaacc480, __in_chrg=<optimized out>) at /tmp/nedit-ng/src/DocumentWidget.cpp:630
#18 0x00002b7ed6652228 in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#19 0x00002b7ed5a4e0db in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#20 0x00002b7ed5a0fd8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#21 0x00002b7ed5a16f68 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#22 0x00002b7ed6628be6 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#23 0x00002b7ed662b503 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#24 0x00002b7ed6677ab3 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#25 0x00002b7edaf2e099 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#26 0x00002b7edaf2e3f8 in g_main_context_iterate.isra.19 () at /lib64/libglib-2.0.so.0
#27 0x00002b7edaf2e4ac in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#28 0x00002b7ed667745c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#29 0x00002b7ed66276db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#30 0x00002b7ed662fc04 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#31 0x0000000000489a5c in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /tmp/nedit-ng/src/nedit.cpp:133
```

**Comment by eteran** [comment]
I'll take a look at this ASAP!

**Comment by eteran** [comment]
Should be fixed in the latest push to master

**Comment by marilmanen** [comment]
I tested with commit b9239066 and I still get the same crash. I double checked make and install, so it looks like the issue is not fixed.

**Comment by eteran** [comment]
That's unfortunate, I could have sworn that I couldn't reproduce it anymore. I'll look into it more tomorow.

**Comment by eteran** [comment]
@marilmanen Please try the latest push, I **think** it should complete the fix.

**Comment by marilmanen** [comment]
Confirmed, I can't reproduce the issue anymore
