### ISSUE TITLE
Crash when initializing an array in a macro file loaded from autoload.nm

### ISSUE THREAD

**Issue by afeblot** [eteran/nedit-ng#27]
On nedit-ng 27e11d4,

with the following autoload.nm:
```
load_macro_file("/......../nedit-ng/other.nm")
```

and the following other.nm:
```
# without the comment, it works fine
$an_array[0] = "value"
```

I get a Segmentation fault in:

```
0   nedit-ng                      	0x00000001090a4699 ContinueMacroEx(std::__1::shared_ptr<MacroContext>&, DataValue*, QString*) + 169 (interpret.cpp:496)
1   nedit-ng                      	0x00000001090a43fa ExecuteMacroEx(DocumentWidget*, std::__1::shared_ptr<Program> const&, gsl::span<DataValue, -1l>, DataValue*, std::__1::shared_ptr<MacroContext>&, QString*) + 1530 (interpret.cpp:470)
2   nedit-ng                      	0x0000000108fbe076 DocumentWidget::runMacroEx(std::__1::shared_ptr<Program> const&) + 774 (DocumentWidget.cpp:5248)
3   nedit-ng                      	0x0000000108fd9683 readCheckMacroStringEx(QWidget*, QString const&, DocumentWidget*, QString const&, int*) + 1491 (macro.cpp:2198)
4   nedit-ng                      	0x0000000108fbf1b3 DocumentWidget::ReadMacroFileEx(QString const&, bool) + 83 (DocumentWidget.cpp:5201)
5   nedit-ng                      	0x0000000108fb9c47 DocumentWidget::ReadMacroInitFileEx() + 55
6   nedit-ng                      	0x0000000109035687 main + 2807 (nedit.cpp:395)

```

**Comment by eteran** [comment]
That is strange, especially that the comment is a factor, but I'll check it out.

**Comment by afeblot** [comment]
In fact, I've the feeling that the macro module has memory management issues, and is crashing more or less randomly on what you throw at it. I found no way to start using the macros I've been using on the X11 version. At one point or another, with different stacks, it crashes.

**Comment by eteran** [comment]
:-/ Well, that's not good. I'll try to get to the bottom of this ASAP!

**Comment by eteran** [comment]
Do the crashes only seem to happen when running via `load_macro_file` ?

**Comment by afeblot** [comment]
No. I brought everything back in autoload.nm, it still crashes.

**Comment by eteran** [comment]
Well, the issue seems to be caused by commit 4ca3815dec6d13330e1ad931bdedf16400423044

I'll see about figuring out what I can do to fix the issue.

**Comment by eteran** [comment]
Fixed as of commit ed4579940c2923e4926415c641832457ed101e0b ? Let me know if you continue to run into crashes.

**Comment by afeblot** [comment]
It's better, as it's now able to load the secondary nm file, however, it's still crashing while executing the macro `highlight_all_selection_and_search_next`:
[rangeset.nm.txt](https://github.com/eteran/nedit-ng/files/1713667/rangeset.nm.txt)
Maybe a totally different issue though.

```
0   org.qt-project.QtCore         	0x000000011009b91e QMimeData::hasText() const + 14
1   nedit-ng                      	0x000000010efb1a72 MainWindow::SearchForSelectedEx(DocumentWidget*, TextArea*, Direction, SearchType, WrapMode) + 66 (MainWindow.cpp:6402)
2   nedit-ng                      	0x000000010efb154d MainWindow::action_Find_Selection(DocumentWidget*, Direction, SearchType, WrapMode) + 221 (atomic:986)
3   nedit-ng                      	0x000000010ef8e352 findSelectionMS(DocumentWidget*, gsl::span<DataValue, -1l>, DataValue*) + 130 (variant.hpp:1434)
4   nedit-ng                      	0x000000010f04d667 callSubroutine() + 247 (interpret.cpp:1542)
5   nedit-ng                      	0x000000010f03fc6b ContinueMacroEx(std::__1::shared_ptr<MacroContext>&, DataValue*, QString*) + 171 (interpret.cpp:499)
6   nedit-ng                      	0x000000010f03f9ca ExecuteMacroEx(DocumentWidget*, Program*, gsl::span<DataValue, -1l>, DataValue*, std::__1::shared_ptr<MacroContext>&, QString*) + 1514 (interpret.cpp:470)
7   nedit-ng                      	0x000000010ef5991c DocumentWidget::runMacroEx(Program*) + 668 (DocumentWidget.cpp:5250)
8   nedit-ng                      	0x000000010ef5fe8c DocumentWidget::DoMacroEx(QString const&, QString const&) + 172
9   nedit-ng                      	0x000000010efbfa66 MainWindow::DoNamedMacroMenuCmd(DocumentWidget*, TextArea*, QString const&, CommandSource) + 86 (qstring.h:1119)
10  nedit-ng                      	0x000000010efbf987 MainWindow::action_Macro_Menu_Command(DocumentWidget*, QString const&) + 151 (atomic:986)
11  nedit-ng                      	0x000000010efac744 MainWindow::macroTriggered(QAction*) + 180 (qstring.h:1119)
12  org.qt-project.QtCore         	0x00000001100a78eb QMetaObject::activate(QObject*, int, int, void**) + 2347
13  org.qt-project.QtWidgets      	0x000000010f24fbf0 QActionGroup::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 1104
14  org.qt-project.QtCore         	0x00000001100a7b4a QMetaObject::activate(QObject*, int, int, void**) + 2954
15  org.qt-project.QtWidgets      	0x000000010f24cf85 QAction::activate(QAction::ActionEvent) + 309
16  org.qt-project.QtCore         	0x000000011009fdc4 QObject::event(QEvent*) + 788
17  org.qt-project.QtWidgets      	0x000000010f24ce3a QAction::event(QEvent*) + 234
18  org.qt-project.QtWidgets      	0x000000010f2569a2 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 306
19  org.qt-project.QtWidgets      	0x000000010f257cbf QApplication::notify(QObject*, QEvent*) + 383
20  org.qt-project.QtCore         	0x000000011007697f QCoreApplication::notifyInternal2(QObject*, QEvent*) + 159
21  org.qt-project.QtCore         	0x0000000110077b32 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 850
22  libqcocoa.dylib               	0x00000001131b11ee QCocoaEventDispatcherPrivate::processPostedEvents() + 190
23  libqcocoa.dylib               	0x00000001131b1aa1 QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 33
24  com.apple.CoreFoundation      	0x00007fff385dba21 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
25  com.apple.CoreFoundation      	0x00007fff3869326c __CFRunLoopDoSource0 + 108
26  com.apple.CoreFoundation      	0x00007fff385beab0 __CFRunLoopDoSources0 + 208
27  com.apple.CoreFoundation      	0x00007fff385bdf2d __CFRunLoopRun + 1293
28  com.apple.CoreFoundation      	0x00007fff385bd787 CFRunLoopRunSpecific + 487
29  com.apple.HIToolbox           	0x00007fff378cae26 RunCurrentEventLoopInMode + 286
30  com.apple.HIToolbox           	0x00007fff378cab96 ReceiveNextEventCommon + 613
31  com.apple.HIToolbox           	0x00007fff378ca914 _BlockUntilNextEventMatchingListInModeWithFilter + 64
32  com.apple.AppKit              	0x00007fff35b95f5f _DPSNextEvent + 2085
33  com.apple.AppKit              	0x00007fff3632bb4c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
34  com.apple.AppKit              	0x00007fff35b8ad6d -[NSApplication run] + 764
35  libqcocoa.dylib               	0x00000001131b089d QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2397
36  org.qt-project.QtCore         	0x0000000110072502 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 418
37  org.qt-project.QtCore         	0x0000000110077092 QCoreApplication::exec() + 402
38  nedit-ng                      	0x000000010efd1f0b main + 7195 (nedit.cpp:448)
```

**Comment by eteran** [comment]
Hmm, I'm having trouble reproducing this particular crash. Here's what I'm trying to do:

autoload.nm

    load_macro_file("/home/eteran/.config/nedit-ng/rangeset.nm")

rangeset.nm

    <you

**Comment by eteran** [comment]
Actually, I think I know what the issue is! The line in question is:

    const QMimeData *mimeData = QApplication::clipboard()->mimeData(QClipboard::Selection);

I am willing to bet that this function returns `NULL` on platforms that don't support a selection, such as OSX.

There is a workaround, but it'll take a little doing. Basically, nedit-ng (and nedit) has two concepts of a selection. The one that X11 is aware of, and the one that is used internally to represent the selection in buffer. I'll just have to make it fall back on internal one if selections aren't supported on the platform.

Based on this, I'm going to close this bug since it is a different issue.

**Comment by eteran** [comment]
Latest push should (hopefully) address the latest crash you had.

**Comment by afeblot** [comment]
Yes, it did 👍 
You're awesome, thanks!
