### ISSUE TITLE
correspondence between macro commands (some macro functions not working correctly)

### ISSUE THREAD

**Issue by caduser2k** [eteran/nedit-ng#36]
Hi,

what is the correspondence between the nedit-ng and the original nedit macro commands?

I have several macro commands installed to work with background menus (for example, open_dailog(). open_select() close(), etc) that seem to not work.

Thanks.

**Comment by eteran** [comment]
They **should** work. nedit-ng re-uses the macro language of nedit, and I've done my best to accurately reproduce the functionality.

Can you provide some simple examples which I can use to reproduce the issue?

**Comment by caduser2k** [comment]
Hi, Ethan.

thanks for the promptly reply!

And sure, no problem. Here's the line of the _config.ini_ file, imported with nedit-import, that describes the background macros I use:

_`nedit.bgMenuCommands=\tFile>Open:Ctrl+O:: {\n\t\topen_dialog()\n\t}\n\tFile>Open selected:Ctrl+Y:R: {\n\t\topen_selected()\n\t}\n\tFile>Close:Ctrl+W:: {\n\t\tclose()\n\t}\n\tFile>Print:Ctrl+P:: {\n\t\tprint()\n\t}\n\tFile>Print selection::R: {\n\t\tprint_selection()\n\t}\n\tFile>Save:Ctrl+S:: {\n\t\tsave()\n\t}\n\tFile>Save as::: {\n\t\tsave_as_dialog()\n\t}\n\tFile>Save all::: {\n\t\tSave_all()\n\t}\n\tEdit>Undo:Ctrl+Z:: {\n\t\tundo()\n\t}\n\tEdit>Uppercase:Ctrl+6:R: {\n\t\tuppercase()\n\t}\n\tEdit>Lowercase:Ctrl+Shift+6:R: {\n\t\tlowercase()\n\t}\n\tEdit>Redo:Ctrl+Shift+Z:: {\n\t\tredo()\n\t}\n\tEdit>Save selection:Ctrl+Shift+Z:: {\n\t\tSave_selection()\n\t}\n\tSearch>Search:Ctrl+Shift+R:: {\n\t\tfind_dialog(\"keep\")\n\t}\n\tSearch>Search again:Ctrl+Shift+G:: {\n\t\tfind_again()\n\t}\n\tSearch>Search selection:Ctrl+Shift+H:R: {\n\t\tfind_selection()\n\t}\n\tSearch>Replace:Ctrl+Shift+R:: {\n\t\treplace_dialog(\"keep\")\n\t}\n\tCut:Ctrl+X:R: {\n\t\tcut_clipboard()\n\t}\n\tCopy:Ctrl+C:R: {\n\t\tcopy_clipboard()\n\t}\n\tPaste:Ctrl+V:: {\n\t\tpaste_clipboard()\n\t}`_

(some of these commands are defined in a macro file, which I have also tried to load manually, like the following code for _Save selection_:

_```
define save_selection {
	saveto = string_dialog("Enter file name","OK")
	find_file = shell_command("ls " saveto , "")
	file_exist = search_string(find_file,"File not found",0)
	if (file_exist == -1) {
		beep()
		choice = dialog("File already exists, overwrite it?", "Yes", "No")
	} else {
		choice = 1
	}
	if (choice == 1) 
	{
		success = write_file(get_selection(), saveto)
		if (success == 0)
		dialog("Could not save file")
	}
}
``_
)

But some of the commands, like, for _Lowercase_ or _Replace_, which are just bindkeys, also don't work.

Let me know what yo think.

Best regards,

**Comment by eteran** [comment]
Oh wow, you found a pretty big oversight! I believe that the issue is simply that the handler for the context menu isn't being called. I think once I fix that, it'll all "just work". I'll follow up shortly.

**Comment by eteran** [comment]
Should be fixed. Please re-open the issue if you continue to experience any issues!

**Comment by caduser2k** [comment]
Thanks, Evan.
I've updated to version 2018.3-1.2 (opensuse 42.3) but I still see the same issues.

**Comment by eteran** [comment]
please try the master branch since I did not do a new release yet.

**Comment by caduser2k** [comment]
Oh, OK. I'll do that. Thanks very much.

Best regards,
