### ISSUE TITLE
Detached Tab open new window without correct size

### ISSUE THREAD

**Issue by patricevenant** [eteran/nedit-ng#75]
When I detach a tab, the new window size doesn't follow the setting 'Initial Window Size'

**Comment by anjohnson** [comment]
This is also true of a few other places where new windows get created. They may have a common fix...

**Comment by eteran** [comment]
Should have a common fix, I'll look into it tomorrow.

**Comment by eteran** [comment]
Should be fixed. @anjohnson , please re-open this and let me know if any other places don't respect this setting. I could only find 3 places in the code where new windows are created and they all **look** like they should.

**Comment by anjohnson** [comment]
Detach tab now creates correctly-sized windows so I think this specific issue is fixed, but `nc-ng` still creates new windows at the wrong size for me. It still isn't finding any existing server windows, so this is when using that fall-back path.

Sorry, can't re-open this issue as I don't have the necessary rights to do so.

**Comment by eteran** [comment]
Well, we already have an issue to track the nc-ng issues that I'm still trying to sort out, so I don't think it should be necessary to open this one too.
